import transportBasemapLayers from './transport-basemap-layers'
import {
  AdminBoundaries,
  Energy,
  Financial,
  Population,
  Public,
  Transport,
} from '../../icons'
import theme from '../theme'
const { colors } = theme

export default [
  {
    id: 'admin',
    label: 'Administrative Boundaries',
    icon: AdminBoundaries,
    description:
      'Detailed dataset of country administrative both large and small scale.',
    controls: [
      {
        id: 'counties',
        label: 'Counties',
        defaultVisibility: false,
        legend: 'none',
        layerIds: ['counties', 'admin-1-boundary', 'admin-1-boundary-bg'],
        info: '',
      },
      {
        id: 'sub-counties',
        label: 'Sub-Counties',
        defaultVisibility: false,
        legend: 'none',
        layerIds: ['sub-counties'],
        info: '',
      },
      {
        id: 'wards',
        label: 'Wards',
        defaultVisibility: false,
        legend: 'none',
        layerIds: ['wards'],
        info: '',
      },
    ],
  },
  {
    id: 'energy',
    label: 'Energy',
    icon: Energy,
    description:
      'Location of mini-grids, transmission lines, fuels & technologies used.',
    controls: [
      {
        id: 'gridfinder',
        label: 'Gridfinder',
        defaultVisibility: false,
        legend: { type: 'line', color: colors.highlight },
        layerIds: ['gridfinder'],
        info: '',
      },
      {
        id: 'census',
        label: 'Census',
        info: '',
        subcontrols: [
          {
            id: 'Conventional Households',
            label: 'Conventional Households',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 30000, max: 1500000 },
              domain: [30000, 1500000],
              unit: '#',
            },
            layerIds: ['Conventional Households'],
            info: '',
          },
          {
            id: 'Main Electricity',
            label: 'Main Electricity',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 50, max: 80 },
              domain: [0, 100],
              unit: '%',
            },
            layerIds: ['Main Electricity'],
            info: '',
          },
          {
            id: 'Low-Quality Stopgap Total',
            label: 'Low-Quality Stopgap Total',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 50, max: 80 },
              domain: [0, 80],
              unit: '%',
            },
            layerIds: ['Low-Quality Stopgap Total'],
            info: '',
          },
          {
            id: 'Kerosene (Total)',
            label: 'Kerosene (Total)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Kerosene (Total)'],
            info: '',
          },
          {
            id: 'Paraffin Pressure Lamp',
            label: 'Paraffin Pressure Lamp',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 10 },
              domain: [0, 10],
              unit: '%',
            },
            layerIds: ['Paraffin Pressure Lamp'],
            info: '',
          },
          {
            id: 'Paraffin Lantern',
            label: 'Paraffin Lantern',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Paraffin Lantern'],
            info: '',
          },
          {
            id: 'Paraffin Tin Lamp',
            label: 'Paraffin Tin Lamp',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Paraffin Tin Lamp'],
            info: '',
          },
          {
            id: 'Gas Lamp',
            label: 'Gas Lamp',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Gas Lamp'],
            info: '',
          },
          {
            id: 'Wood',
            label: 'Wood',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Wood'],
            info: '',
          },
          {
            id: 'Solar (Total)',
            label: 'Solar (Total)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Solar (Total)'],
            info: '',
          },
          {
            id: 'Solar',
            label: 'Solar',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Solar'],
            info: '',
          },
          {
            id: 'Torch / Spotlight (Solar-Charged)',
            label: 'Torch / Spotlight (Solar-Charged)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Torch / Spotlight (Solar-Charged)'],
            info: '',
          },
          {
            id: 'Torch / Spotlight (Dry Cells))',
            label: 'Torch / Spotlight (Dry Cells))',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Torch / Spotlight (Dry Cells))'],
            info: '',
          },
          {
            id: 'Candle',
            label: 'Candle',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Candle'],
            info: '',
          },
          {
            id: 'Battery (Car-Charged)',
            label: 'Battery (Car-Charged)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Battery (Car-Charged)'],
            info: '',
          },
          {
            id: 'Generator (Diesel / Petrol)',
            label: 'Generator (Diesel / Petrol)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Generator (Diesel / Petrol)'],
            info: '',
          },
          {
            id: 'Biogas',
            label: 'Biogas',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Biogas'],
            info: '',
          },
          {
            id: 'Not Stated',
            label: 'Not Stated',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Not Stated'],
            info: '',
          },
          {
            id: 'Cooking - Electricity',
            label: 'Cooking - Electricity',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Electricity'],
            info: '',
          },
          {
            id: 'Cooking - Paraffin',
            label: 'Cooking - Paraffin',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Paraffin'],
            info: '',
          },
          {
            id: 'Cooking - Gas (LPG)',
            label: 'Cooking - Gas (LPG)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Gas (LPG)'],
            info: '',
          },
          {
            id: 'Cooking - Biogas',
            label: 'Cooking - Biogas',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Biogas'],
            info: '',
          },
          {
            id: 'Cooking - Firewood',
            label: 'Cooking - Firewood',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Firewood'],
            info: '',
          },
          {
            id: 'Cooking - Charcoal',
            label: 'Cooking - Charcoal',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Charcoal'],
            info: '',
          },
          {
            id: 'Cooking - Solar',
            label: 'Cooking - Solar',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Solar'],
            info: '',
          },
          {
            id: 'Cooking - Not Stated',
            label: 'Cooking - Not Stated',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Not Stated'],
            info: '',
          },
        ],
      },
    ],
  },
  {
    id: 'finance',
    label: 'Financial Services',
    icon: Financial,
    description: 'Locations of Banks, Micro-finances and SACCOs.',
    controls: [
      {
        id: 'banks',
        label: 'Banks',
        defaultVisibility: false,
        legend: { type: 'dot', color: '#679289' },
        layerIds: ['banks'],
        info: '',
      },
      {
        id: 'mfi',
        label: 'MFIs',
        defaultVisibility: false,
        legend: { type: 'dot', color: '#C8D6AF' },
        layerIds: ['mfi'],
        info: '',
      },
      {
        id: 'sacco',
        label: 'SACCOs',
        defaultVisibility: false,
        legend: { type: 'dot', color: '#1D7874' },
        layerIds: ['sacco'],
        info: '',
      },
    ],
  },
  {
    id: 'population',
    label: 'Population',
    icon: Population,
    description: 'Population density, Night Lights and Mobile Phone Coverage.',
    controls: [
      {
        id: 'arc',
        label: 'Population Density (ARC 2016)',
        defaultVisibility: false,
        legend: 'none',
        layerIds: ['population-density'],
        info: '',
      },
      // 'fb-population': {
      //   label: 'Facebook Population',
      //   defaultVisibility: false,
      //   layerIds: ['fb-population'],
      //   info: '',
      // },
      // nightlights: {
      //   label: 'Night Lights',
      //   defaultVisibility: false,
      //   layerIds: ['night-lights'],
      //   info: '',
      // },
    ],
  },
  {
    id: 'facilities',
    label: 'Public facilities',
    icon: Public,
    description:
      'Locations of Schools, Doctors, Hospitals and other Health Institutions.',
    controls: [
      {
        id: 'health',
        label: 'Health Facilities',
        defaultVisibility: false,
        legend: { type: 'dot', color: '#6A9FB4' },
        layerIds: ['health'],
        info: '',
      },
      {
        id: 'education',
        label: 'Education Facilities',
        defaultVisibility: false,
        legend: { type: 'dot', color: '#DB93B0' },
        layerIds: ['education'],
        info: '',
      },
    ],
  },
  {
    id: 'transport',
    label: 'Transport',
    icon: Transport,
    description: 'Transport networks, roads and routes.',
    controls: [
      {
        id: 'road',
        label: 'Roads',
        defaultVisibility: false,
        legend: 'none',
        layerIds: transportBasemapLayers,
        info: '',
      },
      // rail: {
      //   label: 'Railway',
      //   defaultVisibility: false,
      //   layerIds: ['rail'],
      //   info: '',
      // },
    ],
  },
]
