import transportBasemapLayers from './transport-basemap-layers'

import {
  AdminBoundaries,
  Energy,
  Financial,
  Population,
  Public,
  Transport,
} from '../../icons'

export default {
  admin: {
    label: 'Administrative Boundaries',
    icon: AdminBoundaries,
    description:
      'Detailed dataset of country administrative both large and small scale.',
    controls: {
      counties: {
        label: 'Counties',
        defaultVisibility: false,
        legend: 'none',
        layerIds: ['counties', 'admin-1-boundary', 'admin-1-boundary-bg'],
        info: '',
      },
      'sub-counties': {
        label: 'Sub-Counties',
        defaultVisibility: false,
        legend: 'none',
        layerIds: ['sub-counties'],
        info: '',
      },
      wards: {
        label: 'Wards',
        defaultVisibility: false,
        legend: 'none',
        layerIds: ['wards'],
        info: '',
      },
    },
  },
  energy: {
    label: 'Energy',
    icon: Energy,
    description:
      'Location of mini-grids, transmission lines, fuels & technologies used.',
    controls: {
      gridfinder: {
        label: 'Gridfinder',
        defaultVisibility: false,
        legend: 'none',
        layerIds: ['gridfinder'],
        info: '',
      },
      census: {
        label: 'Census',
        info: '',
        subcontrols: {
          'Conventional Households': {
            label: 'Conventional Households',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 30000, max: 1500000 },
              domain: [30000, 1500000],
              unit: '#',
            },
            layerIds: ['Conventional Households'],
            info: '',
          },
          'Main Electricity': {
            label: 'Main Electricity',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 50, max: 80 },
              domain: [0, 100],
              unit: '%',
            },
            layerIds: ['Main Electricity'],
            info: '',
          },
          'Low-Quality Stopgap Total': {
            label: 'Low-Quality Stopgap Total',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 50, max: 80 },
              domain: [0, 80],
              unit: '%',
            },
            layerIds: ['Low-Quality Stopgap Total'],
            info: '',
          },
          'Kerosene (Total)': {
            label: 'Kerosene (Total)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Kerosene (Total)'],
            info: '',
          },
          'Paraffin Pressure Lamp': {
            label: 'Paraffin Pressure Lamp',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 10 },
              domain: [0, 10],
              unit: '%',
            },
            layerIds: ['Paraffin Pressure Lamp'],
            info: '',
          },
          'Paraffin Lantern': {
            label: 'Paraffin Lantern',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Paraffin Lantern'],
            info: '',
          },
          'Paraffin Tin Lamp': {
            label: 'Paraffin Tin Lamp',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Paraffin Tin Lamp'],
            info: '',
          },
          'Gas Lamp': {
            label: 'Gas Lamp',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Gas Lamp'],
            info: '',
          },
          Wood: {
            label: 'Wood',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Wood'],
            info: '',
          },
          'Solar (Total)': {
            label: 'Solar (Total)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Solar (Total)'],
            info: '',
          },
          Solar: {
            label: 'Solar',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Solar'],
            info: '',
          },
          'Torch / Spotlight (Solar-Charged)': {
            label: 'Torch / Spotlight (Solar-Charged)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Torch / Spotlight (Solar-Charged)'],
            info: '',
          },
          'Torch / Spotlight (Dry Cells))': {
            label: 'Torch / Spotlight (Dry Cells))',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Torch / Spotlight (Dry Cells))'],
            info: '',
          },
          Candle: {
            label: 'Candle',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Candle'],
            info: '',
          },
          'Battery (Car-Charged)': {
            label: 'Battery (Car-Charged)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Battery (Car-Charged)'],
            info: '',
          },
          'Generator (Diesel / Petrol)': {
            label: 'Generator (Diesel / Petrol)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Generator (Diesel / Petrol)'],
            info: '',
          },
          Biogas: {
            label: 'Biogas',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Biogas'],
            info: '',
          },
          'Not Stated': {
            label: 'Not Stated',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Not Stated'],
            info: '',
          },
          'Cooking - Electricity': {
            label: 'Cooking - Electricity',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Electricity'],
            info: '',
          },
          'Cooking - Paraffin': {
            label: 'Cooking - Paraffin',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Paraffin'],
            info: '',
          },
          'Cooking - Gas (LPG)': {
            label: 'Cooking - Gas (LPG)',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Gas (LPG)'],
            info: '',
          },
          'Cooking - Biogas': {
            label: 'Cooking - Biogas',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Biogas'],
            info: '',
          },
          'Cooking - Firewood': {
            label: 'Cooking - Firewood',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Firewood'],
            info: '',
          },
          'Cooking - Charcoal': {
            label: 'Cooking - Charcoal',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Charcoal'],
            info: '',
          },
          'Cooking - Solar': {
            label: 'Cooking - Solar',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Solar'],
            info: '',
          },
          'Cooking - Not Stated': {
            label: 'Cooking - Not Stated',
            defaultVisibility: false,
            legend: {
              type: 'gradient',
              defaultRange: { min: 0, max: 50 },
              domain: [0, 50],
              unit: '%',
            },
            layerIds: ['Cooking - Not Stated'],
            info: '',
          },
        },
      },
    },
  },
  finance: {
    label: 'Financial Services',
    icon: Financial,
    description: 'Locations of Banks, Micro-finances and SACCOs.',
    controls: {
      banks: {
        label: 'Banks',
        defaultVisibility: false,
        legend: { type: 'dot', color: '#679289' },
        layerIds: ['banks'],
        info: '',
      },
      mfi: {
        label: 'MFIs',
        defaultVisibility: false,
        legend: { type: 'dot', color: '#C8D6AF' },
        layerIds: ['mfi'],
        info: '',
      },
      sacco: {
        label: 'SACCOs',
        defaultVisibility: false,
        legend: { type: 'dot', color: '#1D7874' },
        layerIds: ['sacco'],
        info: '',
      },
    },
  },
  population: {
    label: 'Population',
    icon: Population,
    description: 'Population density, Night Lights and Mobile Phone Coverage.',
    controls: {
      arc: {
        label: 'Population Density (ARC 2016)',
        defaultVisibility: false,
        legend: 'none',
        layerIds: ['population-density'],
        info: '',
      },
      // 'fb-population': {
      //   label: 'Facebook Population',
      //   defaultVisibility: false,
      //   layerIds: ['fb-population'],
      //   info: '',
      // },
      // nightlights: {
      //   label: 'Night Lights',
      //   defaultVisibility: false,
      //   layerIds: ['night-lights'],
      //   info: '',
      // },
    },
  },
  facilities: {
    label: 'Public facilities',
    icon: Public,
    description:
      'Locations of Schools, Doctors, Hospitals and other Health Institutions.',
    controls: {
      health: {
        label: 'Health Facilities',
        defaultVisibility: false,
        legend: { type: 'dot', color: '#6A9FB4' },
        layerIds: ['health'],
        info: '',
      },
      education: {
        label: 'Education Facilities',
        defaultVisibility: false,
        legend: { type: 'dot', color: '#DB93B0' },
        layerIds: ['education'],
        info: '',
      },
    },
  },
  transport: {
    label: 'Transport',
    icon: Transport,
    description: 'Transport networks, roads and routes.',
    controls: {
      road: {
        label: 'Roads',
        defaultVisibility: false,
        legend: 'none',
        layerIds: transportBasemapLayers,
        info: '',
      },
      // rail: {
      //   label: 'Railway',
      //   defaultVisibility: false,
      //   layerIds: ['rail'],
      //   info: '',
      // },
    },
  },
}
